spring:
  application:
    name: server-config
  cloud:
    config:
      server:
        git:
          uri: git@github.com:WenLongUP/spring-cloud.git
          default-label: master
          search-paths: config
server:
  port: 8889